# The title
title: dribba.me

# Optional subtitle
# subTitle: David Ribba's Blog

# Author - used by atom feed
author: David Ribba

# The description
description: |
 I'm a passionate software developer that discovered the world of Functional Programming
 not long ago, I have been working with Scala, Java and JavaScript for a while, so, that and some
 if my emotions is all you can expect form this blog.

disqus_shortname: dribba