# The title
title: dribba.me

# Optional subtitle
subTitle: David Ribba's Blog

# Author - used by atom feed
author: David Ribba

# The description
description: |
 I don't really have a description 
 for the blog yet.
